In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Gamer\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [ ]:
a = 1
c = 0
start = datetime.now()
for i in range(len(a)):
    c+= a[i]*b[i]
printf

In [3]:
data = [1, 2, 3, 4, 5.0]
data = np.array(data)
print(f"OG Data: {data}")
print(type(data))
print(data.dtype)
data = np.array(data, dtype=np.int64)
print(f"Altered Data: {data}")
print(type(data))
print(data.dtype)

OG Data: [1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64
Altered Data: [1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [4]:
data = np.zeros((1,5))
print(data)

[[0. 0. 0. 0. 0.]]


In [5]:
data = np.ones((3,3))
print(data)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
data = np.random.rand(5,5)
print(data)

[[0.21812974 0.76604396 0.53895953 0.64078311 0.70032248]
 [0.62256702 0.53742207 0.92799493 0.80671891 0.70180771]
 [0.40589201 0.58330893 0.30841015 0.72756101 0.15071074]
 [0.36484066 0.19827042 0.65161823 0.42341016 0.58086872]
 [0.19821205 0.03039376 0.4626491  0.52702452 0.14403676]]


In [7]:
data = np.full((5,5), 1)
print(data)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
data = np.array([
    [1, 2, 4],
    [5, 8, 9],
    [6, 3, 7],
])
print(data)

[[1 2 4]
 [5 8 9]
 [6 3 7]]


In [10]:
print(data.ndim)

2


In [11]:
row, col = data.shape[:2]
print(f"rows: {row}")
print(f"cols: {col}")

rows: 3
cols: 3


In [12]:
data = np.arange(9)
print(data)
print(data.shape)

a = np.reshape(data, (3,3))
print(a)

b = np.reshape(data, (3,-1))
print(b)

c = np.reshape(data, (-1,3))
print(c)

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
data = np.array([
    [2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11]
    ])
print(data)

data = np.transpose(data)
print(data)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]


In [14]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data)
print(data[4])
print(data[-1])
data[0] = 200
print(data)

[ 1  2  3  4  5  6  7  8  9 10]
5
10
[200   2   3   4   5   6   7   8   9  10]


In [15]:
data = np.array([
    [2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11]
])

print(data[1][2])
print(data[1, 2])
print(data[:, 3:])

9
9
[[ 5  6]
 [10 11]]


In [16]:
data = np.array([
    [
        [1, 2, 3, 4, 5, 6],
        [4, 5, 6, 1, 0, 0],
        [7, 8, 9, 1, 0, 0],
        [1, 2, 3, 4, 5, 6]
    ],
    [
        [1, 2, 3, 4, 5, 6],
        [4, 5, 6, 1, 0, 0],
        [7, 8, 9, 1, 0, 0],
        [1, 2, 3, 4, 5, 6]
    ]
])

print(data)
print(data[0, 1:3, 1:3])

[[[1 2 3 4 5 6]
  [4 5 6 1 0 0]
  [7 8 9 1 0 0]
  [1 2 3 4 5 6]]

 [[1 2 3 4 5 6]
  [4 5 6 1 0 0]
  [7 8 9 1 0 0]
  [1 2 3 4 5 6]]]
[[5 6]
 [8 9]]


In [17]:
a = np.arange(3)
b = np.arange(3, 6)
print(a)
print(b)

print(np.hstack([a, b]))
print(np.vstack([a, b]))

print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b]))

[0 1 2]
[3 4 5]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [18]:
a = np.full((4, 4),5)
b = np.full((1, 1),1)
print(a)
print(b)

data = a + b
print(data)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
