In [ ]:
import numpy as np

In [19]:
data = [1, 2, 3, 4, 5.0]
data = np.array(data)
print(f"OG Data: {data}")
print(type(data))
print(data.dtype)
data = np.array(data, dtype=np.int64)
print(f"Altered Data: {data}")
print(type(data))
print(data.dtype)

OG Data: [1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64
Altered Data: [1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [20]:
data = np.zeros((1,5))
print(data)

[[0. 0. 0. 0. 0.]]


In [21]:
data = np.ones((3,3))
print(data)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
data = np.random.rand(5,5)
print(data)

[[0.09438848 0.06044209 0.79744661 0.47221346 0.4469577 ]
 [0.77944921 0.59801668 0.1614989  0.06438371 0.12950798]
 [0.55228272 0.71716961 0.53271706 0.42474133 0.86802593]
 [0.55462444 0.62098413 0.65543388 0.43552047 0.51992935]
 [0.7192309  0.98069888 0.13565724 0.81625906 0.13671494]]


In [24]:
data = np.full((5,5), 1)
print(data)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
data = np.array([
    [1, 2, 4],
    [5, 8, 9],
    [6, 3, 7],
])
print(data)

[[1 2 4]
 [5 8 9]
 [6 3 7]]


In [28]:
print(data.ndim)

2


In [29]:
row, col = data.shape[:2]
print(f"rows: {row}")
print(f"cols: {col}")

rows: 3
cols: 3


In [36]:
data = np.arange(9)
print(data)
print(data.shape)

a = np.reshape(data, (3,3))
print(a)

b = np.reshape(data, (3,-1))
print(b)

c = np.reshape(data, (-1,3))
print(c)

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
data = np.array([
    [2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11]
    ])
print(data)

data = np.transpose(data)
print(data)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]


In [42]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data)
print(data[4])
print(data[-1])
data[0] = 200
print(data)

[ 1  2  3  4  5  6  7  8  9 10]
5
10
[200   2   3   4   5   6   7   8   9  10]


In [47]:
data = np.array([
    [2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11]
])

print(data[1][2])
print(data[1, 2])
print(data[:, 3:])

9
9
[[ 5  6]
 [10 11]]


In [56]:
data = np.array([
    [
        [1, 2, 3, 4, 5, 6],
        [4, 5, 6, 1, 0, 0],
        [7, 8, 9, 1, 0, 0],
        [1, 2, 3, 4, 5, 6]
    ],
    [
        [1, 2, 3, 4, 5, 6],
        [4, 5, 6, 1, 0, 0],
        [7, 8, 9, 1, 0, 0],
        [1, 2, 3, 4, 5, 6]
    ]
])

print(data)
print(data[0, 1:3, 1:3])

[[[1 2 3 4 5 6]
  [4 5 6 1 0 0]
  [7 8 9 1 0 0]
  [1 2 3 4 5 6]]]
[[5 6]
 [8 9]]


In [63]:
a = np.arange(3)
b = np.arange(3, 6)
print(a)
print(b)

print(np.hstack([a, b]))
print(np.vstack([a, b]))

print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b]))

[0 1 2]
[3 4 5]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [64]:
a = np.full((4, 4),5)
b = np.full((1, 1),1)
print(a)
print(b)

data = a + b
print(data)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
